spring:
  application:
    name: qr-certificate-system

# QR configuration
qr:
  certificate:
    qr-storage-path: ${QR_STORAGE_PATH:./static/qrs}

server:
  port: ${SERVER_PORT:8019}

logging:
  level:
    root: INFO
    com.hags: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

